### ISSUE TITLE
png

### ISSUE THREAD

**Issue by krisboers** [burkmarr/QGIS-Biological-Recording-Tools#7]
Hi Richard
Fantastic plugin - thanks
I'm working on mammals/bats, so the number of maps is much smaller than in your tutorials. It would be easy if I can influence the size of the .png's. Now they are very small - I can image it would be a problem if I make them 10x bigger if I only need 20 (or even 50) maps. But that way, I can immediately use them in an atlas (paper)
Kind regards
Kris

**Comment by burkmarr** [comment]
Hi Kris,

The answer in your case is to use the print composer. On 'Output options' ('Options' tab) of the Biological Recording Tool, set 'Format' to 'Composer Image' instead of 'Image'.  

First you will need to set up a print composer. On the 'Composition' tab of the composer you will see 'Export settings' where you can set the output resolution of the images produced. By default it is 300 dots per inch, but you can set it higher. You will get much higher quality images from a composer than from the QGIS map view. From the map view, it is simply a 'screen grab' really. Another advantage of using a composer is that you can use scalebars, titles etc. You should look particularly at the section 'Output options' on this help page: http://www.tombio.uk/qgisbiorecstool

With format set to 'Composer Image' you have to click the 'Save temporary map layers as...' button for each map you produce - unlike when format is set to 'Image' and the tool just cycles through all open temp layers. However in your case, where you are only doing a relatively small number of maps, this is not too serious a problem.

Good luck!

Rich

**Comment by krisboers** [comment]
thanks! great help
